### ISSUE TITLE
Stake reward value displayed incorrectly

### ISSUE THREAD

**Issue by eroninjapan** [neutroncoin/neutron#10]
PoS block reward values are displayed as a negative value (i.e. -890.12 NTRN) instead of showing the stake reward value (i.e. 6.1234 NTRN) when initially staked. Closing and reopening the wallet displays the correct values.

**Comment by lucifer911** [comment]
Just want to share.
Ok so Got some payout yesterday.
![screen shot 2017-11-11 at 9 48 41 pm](https://user-images.githubusercontent.com/27394137/32695522-8f5280d4-c72c-11e7-91d4-8de784bd116c.png)
After restarting the wallet amount got change.
![screen shot 2017-11-11 at 9 52 27 pm](https://user-images.githubusercontent.com/27394137/32695532-ac71244a-c72c-11e7-9d67-5bddb7dacacc.png)
