### ISSUE TITLE
Cross compiling from a windows wallet from linux

### ISSUE THREAD

**Issue by saniales** [neutroncoin/neutron#18]
Hello, I am trying to compile the wallet using mingw64 in Ubuntu 17.04 but I can't make anything work
first of all I get the following error:
``` bash
x86_64-w64-mingw32.static-g++ Not Found
```
I try to rename into x86_64-w64-mingw32-g++ and it works but I get another error, telling me boost library is not found (missing some headers) 
Can you help me in compiling to windows from linux? I would really appreciate

**Comment by bigstunta101** [comment]
were you able to get this figured out? i'm also stuck on this step

**Comment by oicu8** [comment]
We have included a Windows Executable in the Releases page. Please Visit:
https://github.com/neutroncoin/neutron/releases
Thanks
