### ISSUE TITLE
qt 5.9.4

### ISSUE THREAD

**Issue by aseedb** [neutroncoin/neutron#22]
Compiling with qt 5.9.4 and qmake 3.1 under ubuntu 16.04 throws lots of errors. This version comes with anaconda python environment distribution. If I unsource anaconda and use ubuntu 16.04 qt 5.5.1 and qmake 3.0 then it compiles happily.

**Comment by adam-waldenberg** [comment]
Anaconda installs a conflicting qmake version that breaks the environment. I consider this an Anaconda bug and not a bug in the neutron code base. Closing.
