### ISSUE TITLE
makefile.unix new files

### ISSUE THREAD

**Issue by collapsedev** [neutroncoin/neutron#23]
makefile.unix:
     obj/rpcdarksend.o \
-    obj/spork.o
+    obj/spork.o \
+    obj/validation.o \
+    obj/txmempool.o

**Comment by eroninjapan** [comment]
@collapsedev Thanks - fixed. Separately, would you be interested/available for some development work for Neutron? Please come by the Discord and message us.

**Comment by collapsedev** [comment]
Not fixed.  obj/txmempool.o not present in makefile.unix.

**Comment by eroninjapan** [comment]
Missed a line when alphabetizing the list. Thanks for catching it.
