### ISSUE TITLE
Does not compile in linux

### ISSUE THREAD

**Issue by collapsedev** [neutroncoin/neutron#26]
Probably you need to cherry-pick this commits:
https://github.com/collapsedev/Neutroncoin_Linux_Daemon/commit/e1dd5fb4d1e3f20141a7e82bbd6abf066ee8c48c
https://github.com/collapsedev/Neutroncoin_Linux_Daemon/commit/7acd03fc1beb488491602833e9baf23b634b4000
https://github.com/collapsedev/Neutroncoin_Linux_Daemon/commit/2597ebf86bc00d843e4a09bb8979e3c8b6593542

**Comment by eroninjapan** [comment]
Thanks, cherry-picked and merged
