### ISSUE TITLE
json createrawtransaction fail

### ISSUE THREAD

**Issue by collapsedev** [neutroncoin/neutron#29]
"When I try to call "createrawtransaction" via json-rpc, I'm getting the error "Invalid parameter, missing vout key"."

Reported bug in bitcointalk thread:
https://bitcointalk.org/index.php?topic=1323468.msg45505146#msg45505146

Condition always false.

**Comment by oicu8** [comment]
This is with the latest pull from the Repo, V2.0.5+? I do remember this problem, thought we solved it.

https://github.com/neutroncoin/neutron/commit/66c0c500b186074f14c6116c1c0136e7bf44657b

**Comment by collapsedev** [comment]
My mistake, closing.
