### ISSUE TITLE
Enforce pay correct masternode breaks PoS consensus

### ISSUE THREAD

**Issue by collapsedev** [neutroncoin/neutron#30]
>ERROR: ConnectBlock() : Stake does not pay correct masternode: actual=9YNgg1SQqKUDRbQaTdKmau6rW7WZDjueBM required=9X1GTtTF9BHhr4S4CsW6pSdnuF9Q7PDSJx
>InvalidChainFound: invalid block=6c478bde8fd1213800c2  height=1485570  trust=315407648972466901915  blocktrust=21603529  date=12/21/18 19:38:24
>InvalidChainFound:  current best=7b8427c4c7fa997439f6  height=1485569  trust=315407648972445298386  blocktrust=21603529  date=12/21/18 19:37:53
>ERROR: SetBestChain() : SetBestChainInner failed
>ERROR: AcceptBlock() : AddToBlockIndex failed
>ERROR: ProcessNewBlock() : AcceptBlock FAILED

Different masternode list in different miners breaks the PoS consensus, and the network.

**Comment by audiotopix** [comment]
Thank you, we appreciate all the help we can get.

**Comment by eroninjapan** [comment]
Would you be able to work on this with us or suggest some pull requests?

**Comment by collapsedev** [comment]
If two PoS miners are not able to select the same masternode address for payment, each miner creates his own fork.

Some options:
-Cancel the fork and restore 60017 rules, this version sync without problems. Diff 0.00437 and block 1488583. Try the hard fork in the future.
-Select some miner of 60018 and fork it again with checkpoints to "not enforced" masternode payment check. (not too fair)
-Relaunch public mining after some point 1482201 block (checkpoint).

The easy way, restore 60017 version.

After this, you can design new consensus rules with more time.
If a client, in initial download status, can not see the next masternode winner address, it's simply a non consensus.

This is a very complex stuff, requires a lot of work and time.

**Comment by barrystyle** [comment]
@collapsedev masternode winners list is meant to be 'identical' amongst hosts; this is how they verify the next mn payment is to the right node; and whether an address is indeed the rightful recipient.

**Comment by collapsedev** [comment]
> @collapsedev masternode winners list is meant to be 'identical' amongst hosts; this is how they verify the next mn payment is to the right node; and whether an address is indeed the rightful recipient.

Should be, but it's not.

**Comment by audiotopix** [comment]
Well then there is what needs to be solved, Why isnt it? being the next question. With how do we make it correct to follow.

**Comment by tbbw** [comment]
Is still bug still around?
I remember discussting this with the dev team on their discord when their solution was "Don't stake coins run a masternode instead it never gets fored off like the stake wallets do".
And when i pointed out that it's not really a fix since MN and POS is part of the coin and i asked what the devfee is used for i got kicked off their discord within 24h so i do not think this is an issue anywhere near their roadmap of things to adress.

Anyhow... best of luck to the project...
The devs/admins/mods on the discord present at the discussion was audiotopix and oicu8 if it is of importance.
And the discussion should still be there unless it got swept under the rug.

**Comment by audiotopix** [comment]
Well this is most interesting,, We have never once told anyone ever to run an mn and not stake, as not staking would mean MNS would not get paid. That is a pretty silly thing to accuse,, The Dev fee has been and always will be used to support the coin, we have done many many things with it including running constant giveaways. With the release of Version 3.0 we have changed ALL private keys,, and MN winners enforcement will be turned on and 100% working in the near future,, we had to learn how to fix several issues Including the MN payments Key, so that addresses can be properly signed and enforced. We have done a great deal of work here and we are not done. 450+ MNs running worldwide, and the network is only getting better as we move forward. The Dev fee supports all the work we do and all of the services we pay for. Including running our seednodes, paying for masternodes.pro subscription, and pandabot, as well as running our community rains / showers / giveaways. Best of luck to you.

**Comment by tbbw** [comment]
@audiotopix Actually... you where the one that said it and i reacted with that was a very silly workaround to something that should be a priority to fix.
You have no idea how big my smile is hearing you now a 1-2 years later saying how silly of a thing that would be to say.

Anyhow... hope that consert in the desert you where doing some audio/light work at that you left to go to for about the same time as i got kicked ( closest thing i can give as a time time frame... if you did not purge me from discord to hide the convo from the community... go back and read it :)

Think the discord username i used at the time was "Rawr" or something.

**Comment by audiotopix** [comment]
@tbbw Im sorry but I would have never told anyone to run a masternode and not stake. Its no matter, your welcome to look over all of our recent work and see that we have corrected the issue in question.
And you are welcome to come back to our Discord anytime.

**Comment by collapsedev** [comment]
" Stake does not pay correct masternode" ruining (sometimes) PoS consensus.

At the moment seems that works. PoS Diff: 0.005, Height: 1794100

**Comment by collapsedev** [comment]
I think that CMasternodeMan::CheckAndRemove removes different inactive masternodes in miner peers with different clock time (or similar condition). Different list of masternodes triggers "Stake does not pay correct masternode" and breaks PoS consensus.
Reorganize blocks fails because the other chain breaks the rules: "Stake does not pay correct masternode" .  If you restart, "correct masternode" not checked; in this case you can sync again.

**Comment by barrystyle** [comment]
CMasternodeMan::CheckAndRemove's purpose is to test and update the state 
of each Masternode list entry, dependent on lack of activity or whether 
the collateral has spent.
All satoshi-based cryptocurrencies automatically cater for different 
timezones by using an offset to keep the clock consistent.

I've seen a lot of unusual statements on this thread.
Enforcing the correct masternode payment is nearly impossible; all 
masternodes will have a slightly different winners list.
Dash has only just made this possible with on-chain deterministic 
masternode lists.
Beforehand, Dash had to rely on the winner's list and the masternodes 
own internal voting system which was complex and inconsistent.
Bashing neutron because it gets the payee incorrect every so often is 
like complaining that your computer is slow.

Additionally, you do not stake on your masternode. Ever. You'd have to 
be deluded to do so.
I reached out to the team a while back regarding a possible upgrade to 
the deterministic platform..

james

**Comment by adam-waldenberg** [comment]
This shouldn't really be a problem and the node should be able to detect it has an invalid block. The network needs to be able to handle incorrect payments and people sabotaging the chain. If somebody can inject a block that breaks or stalls nodes it means we kinda need to do something.

After investigating the daemon there were several bugs in the chain code inside CheckBlock() and Reoriganize() that needed attention and actually stopped the daemon from finding its way back onto the majority chain after a local fork. I think I have fixed these issues at this point - but it needs more testing to confirm I resolved all of it.

**Comment by adam-waldenberg** [comment]
With some reservation for error, I think we have this pinned down now. Many fixes to the Reorganize() code and syncing of the masternode list were needed to resolve it.

Please open a new issue if you find any further issues related to this.

**Comment by collapsedev** [comment]
Still failing:

> ConnectBlock() : *Block 1918047 reward=10.81953 - Expected payouts: Stake=3.31077618, Masternode=6.42680082, Project=1.081953
> ConnectBlock() : Stake pays correct masternode, address=9hZL7YLPQGpdVKtxPuy6EGVVwN8p9pqpPa, block=1918047
> ProcessBlock : winner, payee=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, nBlockHeight=1918048
> AddWinningMasternode : new masternode winner has an equal or higher score - replacing
> ProcessBlock : winner, payee=9knmtFXWYxFvUxjVxfJHRKc7prrZHMsVmG, nBlockHeight=1918049
> AddWinningMasternode : new masternode winner has an equal or higher score - replacing
> ProcessBlock : winner, payee=9dtYKyZfPJzfm4C15zBHQZHzmhx7xUcbjw, nBlockHeight=1918050
> AddWinningMasternode : adding block 1918050
> SetBestChain : new best=fac05c6572fa541d0532  height=1918047  trust=315407689251512765184  blocktrust=69067495  date=02/03/20 23:04:35
> ConnectBlock() : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
> ConnectBlock() : Possible discrepancy found in masternode payment, recalculating payee...
> ProcessBlock : winner, payee=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, nBlockHeight=1918048
> AddWinningMasternode : new masternode winner has an equal or higher score - replacing
> ERROR: ConnectBlock() : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
> 
> InvalidChainFound : invalid block=9cb6f9bd5dd0d6af847d  height=1918048  trust=315407689251590159982  blocktrust=77394798  date=02/03/20 23:06:06
> InvalidChainFound : current best=fac05c6572fa541d0532  height=1918047  trust=315407689251512765184  blocktrust=69067495  date=02/03/20 23:04:35
> ERROR: SetBestChain : SetBestChainInner failed
> ERROR: AcceptBlock() : AddToBlockIndex failed

**Comment by oicu8** [comment]
Can you check `getinfo` and see if the "moneysupply" is correct or small when this happens?
example:
"moneysupply": 45130542.32587000, is correct
vs
"moneysupply": 4034.78949, is incorrect.
Thanks!

**Comment by adam-waldenberg** [comment]
@collapsedev No you are wrong. This is a normal error reported dy design and can happen if you are not quite synced up with the masternode list or if there is a small disagreement on you node with the main chain. The daemon will always recover itself within a few blocks.

If you grep for `Possible discrepancy found in masternode payment` in the debug log you can see that it happens from time to time. It's completely normal.

**Comment by collapsedev** [comment]
`The daemon will always recover itself within a few blocks`
No, the node finds another  "proof-of-stake block" and creates a fork.
If you restart the daemon, sync occurs.

**Comment by adam-waldenberg** [comment]
No that's not how it works @collapsedev .. If it finds another proof of stake block it will re organize onto the consensus chain within a few blocks at most.
We have a spork that controls this behavior and the threshold.

**Comment by collapsedev** [comment]
You should run a staking daemon. I do not known what is supposed to happen. But daemon becomes out of track each few days.

`cat debug.log | grep 'ConnectBlock\|proof-of-stake\| AcceptBlock' | cut -d')' -f2`
> ...
>  : Stake pays correct masternode, address=9X2vMnG6bG3jazUYcXrdfd3jbJ1r1et2VP, block=1918044
>  : *Block 1918045 reward=10.81955 - Expected payouts: Stake=3.3107823, Masternode=6.4268127, Project=1.081955
>  : Stake pays correct masternode, address=9YMM796WtLNAvJw8tFibFdGBWEYmzMsXxB, block=1918045
>  : *Block 1918046 reward=10.81954 - Expected payouts: Stake=3.31077924, Masternode=6.42680676, Project=1.081954
>  : Stake pays correct masternode, address=9nRUfKRTGimqx1192E7MzbAmR6Ut2nmbfX, block=1918046
>  : *Block 1918047 reward=10.81953 - Expected payouts: Stake=3.31077618, Masternode=6.42680082, Project=1.081953
>  : Stake pays correct masternode, address=9hZL7YLPQGpdVKtxPuy6EGVVwN8p9pqpPa, block=1918047
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
>  : AddToBlockIndex failed
> , 1580770902
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
> ERROR: Reorganize : ConnectBlock 9cb6f9bd5dd0d6af847d failed
>  : AddToBlockIndex failed
> 
> ERROR: ProcessNewBlock : AcceptBlock for 341b807a97aa3904e07f17db2e36234cb17139fc6e82a2cf9e83e8110ef4d00f with parent 9cb6f9bd5dd0d6af847d5503c70b78b7ea
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
> ERROR: Reorganize : ConnectBlock 9cb6f9bd5dd0d6af847d failed
>  : AddToBlockIndex failed
> 
> ERROR: ProcessNewBlock : AcceptBlock for 2dd2e9a8a4a787f6d461e95ee3bb262aa5d305318835e65a617cbfe0456cedf9 with parent 341b807a97aa3904e07f17db2e36234cb1
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
> ERROR: Reorganize : ConnectBlock 9cb6f9bd5dd0d6af847d failed
>  : AddToBlockIndex failed
> 
> ERROR: ProcessNewBlock : AcceptBlock for 6b1092a196db249c6e19090246e9af0b1d14944fa1c8b14d9d312cfb5241d30a with parent 2dd2e9a8a4a787f6d461e95ee3bb262aa5
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
> ERROR: Reorganize : ConnectBlock 9cb6f9bd5dd0d6af847d failed
>  : AddToBlockIndex failed
> 
> ERROR: ProcessNewBlock : AcceptBlock for aebec456f8e0ea0d0f6c0c348cde403fc74e84899430ec4cf0ac81230e1dfa89 with parent 6b1092a196db249c6e19090246e9af0b1d
>  : new proof-of-stake block found..
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Stake pays correct masternode, address=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918048
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918049
> ERROR: Reorganize : ConnectBlock 9cb6f9bd5dd0d6af847d failed
>  : AddToBlockIndex failed
> ERROR: ProcessNewBlock : AcceptBlock for 430efcb0f5030f18051d94bdfff17f24c03da2558cf9281fec1430f9c66d5360 with parent aebec456f8e0ea0d0f6c0c348cde403fc7
>  : *Block 1918048 reward=10.81952 - Expected payouts: Stake=3.31077312, Masternode=6.42679488, Project=1.081952
>  : Possible discrepancy found in masternode payment, recalculating payee...
>  : Stake does not pay correct masternode, actual=9T9yiMqhgS9kMdkUZb7wsmEMC38Zcfaw1w required=9WmbzGrr2v3nEe81jbsW9zTMo1YDCRoPaT, block=1918049
>  : *Block 1918049 reward=10.81951 - Expected payouts: Stake=3.31077006, Masternode=6.42678894, Project=1.081951
>  : Stake pays correct masternode, address=9knmtFXWYxFvUxjVxfJHRKc7prrZHMsVmG, block=1918049
>  : *Block 1918050 reward=10.8195 - Expected payouts: Stake=3.310767, Masternode=6.426783, Project=1.08195
>  : Stake pays correct masternode, address=9dtYKyZfPJzfm4C15zBHQZHzmhx7xUcbjw, block=1918049
>  : *Block 1918051 reward=10.81949 - Expected payouts: Stake=3.31076394, Masternode=6.42677706, Project=1.081949
>  : Stake pays correct masternode, address=9hTMC5KsXNBoeNAUy5Y4Z6EY39JZW8A6WP, block=1918049
>  : *Block 1918052 reward=10.81948 - Expected payouts: Stake=3.31076088, Masternode=6.42677112, Project=1.081948
>  : Stake pays correct masternode, address=9ZSLW27xWxLijG9RaGmGENT6wQKhmaH7C3, block=1918049
>  : *Block 1918053 reward=10.81947 - Expected payouts: Stake=3.31075782, Masternode=6.42676518, Project=1.081947
>  : Stake pays correct masternode, address=9ZjZRsCohn2swfjwgQmjqCVFtEqLVzKCvp, block=1918049
>  : *Block 1918054 reward=10.81946 - Expected payouts: Stake=3.31075476, Masternode=6.42675924, Project=1.081946
>  : Stake pays correct masternode, address=9dCpiqFGPLDyMSBAW5PiHr5TRxFNy48Y8U, block=1918049
>  : new proof-of-stake block found..
>  : *Block 1918055 reward=10.81945 - Expected payouts: Stake=3.3107517, Masternode=6.4267533, Project=1.081945
>  : Stake pays correct masternode, address=9nvWYvrp5SXZXJFxHMyp1zSggeud1Mf5J5, block=1918055
>  : *Block 1918056 reward=10.81944 - Expected payouts: Stake=3.31074864, Masternode=6.42674736, Project=1.081944
> ...
> 5000 lines after
> ...
> : Stake pays correct masternode, address=9g5rRxRQr462XhMsHtJnKbB75CL6YzwqzM, block=1919808

> {
>   "version": "v3.0.13",
>   "protocolversion": 60024,
>   "walletversion": 60000,
>

**Comment by adam-waldenberg** [comment]
I have 5 staking wallet running @collapsedev. So I kinda know  how they behave.... To be clear - they have been running since our last release without a single restart or any hickup.

I think I know what this might be, but it's actually unrelated to this issue and it's basically a kind of corruption that happens in the transaction database. It's related to the issue you reported in #36

Open a new issue and provide the full debug log and the content of the `getinfo` and `getdebuginfo` commands so we ca take a look. Most likely it's related to the same thing and we need to update our staking algo to fix it permanently.

Regardless, it's helpful if we can collect as much information as we can.

You can omit your balances from those commands btw.
