### ISSUE TITLE
Compile (Ubuntu 17.04)

### ISSUE THREAD

**Issue by Captain-Flint** [neutroncoin/neutron#6]
Correct:
apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools \
    build-essential libboost-dev libboost-system-dev \
    libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev \
    libssl-dev libdb++-dev **libminiupnpc-dev**

**Comment by eroninjapan** [comment]
Added. Thanks!
